{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "sec-ch-ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "sec-ch-ua-platform": "\"Windows\"",
    "accept": "*/*",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "es-419,es;q=0.9,en;q=0.8"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/orders-filled",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/orders-filled",
  "listenerPath": "/api/*",
  "relativePath": "/api/orders-filled",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/orders-filled",
  "rawRequestPath": "/api/orders-filled",
  "remoteAddress": "/127.0.0.1:60490",
  "requestPath": "/api/orders-filled"
}